Module5 task2
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #10
Opened 2023-01-23 21:20 UTC by JuliaAf

2023-01-26 22:31 UTC, AlexMasterov requested changes

2023-01-26 22:31 UTC, AlexMasterov commented on src/presenter/filter-presenter.js
> +    return [
<details>
<summary>presenter/filter-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/filter-presenter.js#L25-L26
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/filter-presenter.js#L31-L32
</details>

Как ты заметила, содержание тега отображается стилями в верхнем регистре.

Теперь наглядней видно, что можно оставить одно поле и для него использовать значение из перечисления 😃

> Кстати, см. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-7/src/presenter/filter-presenter.js#L25-L56) (уже сделано, но даже лучше)

2023-01-26 22:31 UTC, AlexMasterov commented on src/presenter/filter-presenter.js
> +  #filterPoints(filterType) {
<details>
<summary>presenter/filter-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/filter-presenter.js#L43-L54
</details>

> Обрати внимание, что в нем результат сортировки и копирования не возвращаются из функции и никуда не присваиваются, а просто пропадают

См. прежде [вариант (ожидание) из демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-7/src/presenter/board-presenter.js#L50).

Этот метод можно полностью удалить, а под решение фильтрации, по примеру демо проекта использовать объект-словарь. Далее можно ждать соответствующего задания или пытаться реализовать фильтрацию сразу.

<details>
<summary>Пример словаря</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/utils/filter.js#L3-L6
```js
const filterTypeToFilter = {
  [FilterType.EVERYTHING]: (points) => points.slice(),
  [FilterType.FUTURE]: filterPointsByFuture,
};
```

</details>

Объект-словарь желательно использовать через интерфейс функции, чтобы (по желанию) его можно было заменить на другую структуру, например, `Map`, а при использовании функции сделать такое изменение проще; оно не затронет пользователя функции.

<details>
<summary>Пример интерфейса функции, которая прячет "сложность" работы со словарем</summary>

Экспортировать не словарь, а функцию, которая скрывает работу с нии:
```js
function filterPoints(points, filterType = FilterType.EVERYTHING) {
  return filterTypeToFilter[filterType]?.(points) ?? points.slice();
}

export { filterPoints };
```

</details>

2023-01-26 22:31 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    name: 'offers',
Может так? 😃
```diff
- name: 'offers',
+ name: `${SortType.OFFER}s`,
```

2023-01-26 22:31 UTC, AlexMasterov commented on src/view/sort-view.js
> +      value="sort-${ id }"
<details>
<summary>view/sort-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/view/sort-view.js#L46
</details>

```js
SortType.DAY     // day
evt.target.value // sort-day
```
Из-за этого не работает условие на выбор сортировки по `SortType`.

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/view/filter-view.js#L11

> Свободный атрибут `value`

```diff
- value="sort-${ id }"
+ value="${ id }"
```

2023-01-26 22:31 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    this.#clearPoints();
Всё работает, как должно.

<details>
<summary>mock/mock.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/mock/mock.js#L1-L256
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/mock/mock.js#L1324-L1331
</details>

<details>
<summary>model/points-model.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/model/points-model.js#L4
</details>

#points = Array.from({ length: 15 }, `getRandomPoint`);

Проблема в том, что `getRandomPoint` случайным образом выбирает из массива `points` объект с данными точки маршрута, но таким образом в `#points` модели может попасть несколько копий одного объекта с одним и тем же `id`.

<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/points-presenter.js#L108-L119
</details>

Почему это проблема?

Пример: для 3-х копий одного объекта с одним `id` создается 3 презентера, которые по `.init` добавляются в элемент списка и отображаются в браузере. После этого презентер с ключом `point.id` добавляется в словарь `this.#pointPresenters`:

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/points-presenter.js#L118

Поскольку, в словаре `Map` ключи уникальны, то по итогу из 3-х презентеров туда добавляется последний (через перезапись по ключу предыдущих). Таким образом, в браузере мы видим 3 карточки, а доступ к презентеру имеем только к одной из них, остальные просто не сохраняются в словаре. 

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/presenter/points-presenter.js#L122

Если из 3-х презентеров сохраняется только один последний, то он и удаляется, а остальные продолжают оставаться в элементе списка и отображаться в браузере. Из-за этого _кажется_, что список не очищается, хотя презентеры корректно удаляют элементы из списка.

<details>
<summary>Вариант решения</summary>

```js
// mock/mock.js
const getPoints = () => points.map(({ date_from, date_to, ...point }) => ({
    ...point,
    dateFrom: new Date(date_from),
    dateTo: new Date(date_to),
}));
```
> Заодно удаляем `date_from` и `date_to`

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/b50aed47f1fb01fc3f2930f7407bae4b0434e363/src/model/points-model.js#L4

```diff
- #points = Array.from({ length: 15 }, getRandomPoint);
+ #points = getPoints().slice(0, 5);
```

> Также можно попробовать отфильтровать по `id`, но проще использовать мой пример


</details>

2023-01-26 22:36 UTC, AlexMasterov commented on src/main.js
> +const filterContainer = document.querySelector('.trip-controls__filters');
Пож. раздели элементы и модели пробелом, чтобы выделить их в блоки и упростить чтение. Сейчас все смешано.

2023-01-26 22:40 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +  #handleSortTypeChange = (sortType) => {
Добавь поле классу поле `#currentSortType` и в этом обработчике обновляй его значение на актуальный `SortType` от вью:

```js
this.#currentSortType = sortType;
```

См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-7/src/presenter/board-presenter.js#L125).

> Это потребуется далее

2023-01-26 22:43 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +const sortItems = [
Пож. пока запиши название переменной в формате константы.

Далее можно подумать насчет вариантов генерации списка.

2023-01-27 21:09 UTC, JuliaAf commented on src/presenter/points-presenter.js
> +    name: 'offers',
👍

2023-01-28 21:51 UTC, AlexMasterov commented
👍🏻

2023-01-28 21:51 UTC, merged