6.7. Обновление века (часть 1)
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #11
Opened 2023-01-30 21:43 UTC by JuliaAf

2023-01-31 04:29 UTC, AlexMasterov requested changes

2023-01-31 04:29 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +    if (evt.key === 'Escape') {
Ошибку с отсутствием `.key` объяснил в ТГ и там же предложил возможное решение.

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this._setState(PointFormView.parsePointToState(point));
Лучше вызвать `this._setState` _после_ установки значений полям объекта из параметров, например, в конце конструктора, перед `this._restoreHandlers()`.

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    let selectedDestination = this.#destinations.find((destination) => evt.target.value === destination.name);
.find((destination) => `evt.target.`value === destination.name);

В цикле значение `evt.target.value` не меняется, но его получение происходит повторно, через цепочку обращений двух объектов: `evt.` и `target.`, что неэффективно и ухудшает читаемость.

<details>
<summary>Пример простой оптимизации</summary>

```js
const destinationName = evt.target.value;

this.#destinations.find(({ name }) => name === destinationName);
```
</details>

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.element.querySelector('.event__input--destination').addEventListener('change', this.#destinationChangeHandler);
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L218-L221
</details>

**4x** `this.element`.*

В методе чтобы получить элемент вью геттер [`this.element`](https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/framework/view/abstract-view.js#L30-L36) вызывается повторно 4 раза, что неэффективно и усложняет чтение кода. 

> По ссылке на реализацию геттера можно увидеть, что происходит _каждый раз_ при обращение к `this.element`

Можно получить элемент _один_ раз, используя переменную, и дальше в методе работать с ней.

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
>    constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
Из `createTemplate()` нужно удалить `BLANK_POINT`:

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L50

```diff
- } = point ?? BLANK_POINT; 
+ } = point;
```

И вместо этого задать значение по умолчанию для `point` в конструкторе:

```diff
- constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
+ constructor({ point = BLANK_POINT, destinations, offers, onFormSubmit, onRollupButtonClick }) {
```

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      point: this._state,
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L205
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L43
</details>

Теперь в функцию создания шаблона с разметкой передается объект состояния вью, а не данные с точкой маршрута. У объекта состояния могут быть переопределенные или дополнительные свойства.

 
```diff
- point: this._state,
+ state: this._state,
```

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      destination: selectedDestination.id
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L244-L247
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L249-L251
</details>

`selectedDestination` — это _строка_ и у неё нет `.id` (= `undefined`).

Таким образом `destination` задается значение `undefined`.

<details>
<summary>hint</summary>

Если хочешь в отсутствие данных для введенного направления отобразить пустое поле и скрыть секцию, то проще всего использовать пустую структуру `?? BLANK_DESTINATION`:

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L58

Тогда подобная проверка избыточна:

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L245-L247

С таким решением нужно сделать поле обязательным, добавив в его разметку атрибут `required`, чтобы работала валидация от браузера и было нельзя сделать `submit` (= `Save`) формы с пустым полем.

> Решений больше

См. ТЗ:
> Введённые пользователем данные экранируются

В таком решение название направления, которого нет в данных с сервера, не отобразиться в поле. Поэтому можно не экранировать вывод названия направления с помощью библиотеки `he`, разве что сделать это "под задание" и букве формализма ТЗ.

Оставляю это на твое усмотрение
</details>

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    let selectedDestination = this.#destinations.find((destination) => evt.target.value === destination.name);
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L244
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fe02d350aae8b945ffa1ca3507b84f7d77e33c93/src/view/point-form-view.js#L54-L58
</details>

[Д11](https://up.htmlacademy.ru/ecmascript/19/criteries#d11) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

См. истоки проблемы: https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/7#discussion_r1062125406

Думаю, что некритично. Особенно в отсутствие времени

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/215662866-149aecce-5177-4f5e-8592-75dfbe30bc39.png)
![image](https://user-images.githubusercontent.com/700213/215664150-17a641f7-52d1-42a9-af47-73a64784e7b7.png)

![image](https://user-images.githubusercontent.com/700213/215663926-8205048c-711d-495a-b5ee-9e9f6b4996cc.png)

</details>

См. ТЗ:
> Стоимость. Целое положительное число

Желательно доработать в этом задание.

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
Изменение стоимости сбрасывается при изменение типа и направления, возвращаясь к исходному значению.

Желательно разобраться и доработать в этом задание.

2023-01-31 04:29 UTC, AlexMasterov commented on src/view/point-form-view.js
Изменения в предложениях сбрасываются при изменение направления, возвращаясь к исходном значениям (выбору).

Желательно разобраться и доработать в этом задание.

2023-01-31 06:56 UTC, AlexMasterov commented on src/view/point-form-view.js
Сейчас можно сохранить форму с пустым полем стоимости.

Желательно доработать в этом задание.

2023-01-31 11:56 UTC, JuliaAf commented on src/view/point-form-view.js
> +    this._setState(PointFormView.parsePointToState(point));
можешь объяснить логику этого, чтобы мне не делать в дальнейшем таких ошибок?

2023-01-31 12:13 UTC, JuliaAf commented on src/view/point-form-view.js
>    constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
это можешь тоже пжл объяснить

2023-01-31 12:49 UTC, JuliaAf commented on src/view/point-form-view.js
> +      destination: selectedDestination.id
до he не дошла еще, остальное сделала

2023-01-31 13:20 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      offers: [],
См. ТЗ:
> При смене пункта назначения блок с описанием перерисовывается; или скрывается, если у пункта назначения нет описания и фотографий к нему. Остальные данные, введённые пользователем, должны быть сохранены

Смена направления не должна сбрасывать выбранные предложения.

2023-01-31 13:20 UTC, AlexMasterov commented on src/view/point-form-view.js
> +            <input class="event__input  event__input--destination" id="event-destination-1" type="text" name="event-destination" value="${ destinationName ?? '' }" list="destination-list-1" required>
```diff
- value="${ destinationName ?? '' }"
+ value="${ destinationName }"
```

2023-01-31 13:20 UTC, AlexMasterov commented on src/view/point-form-view.js
> +function createTemplate({ state, destinations = [], offers = [] }) {
```diff
- function createTemplate({ state, destinations = [], offers = [] }) {
+ function createTemplate({ state, destinations, offers }) {
```

2023-01-31 13:21 UTC, AlexMasterov commented on src/view/point-form-view.js
Не реализовано.

2023-01-31 13:22 UTC, merged

2023-02-01 05:39 UTC, AlexMasterov commented on src/view/point-form-view.js
>    constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
Что именно?

Если при создание экземпляра класса (объекта) `PointFormView` не задать значение для `point`, то оно будет задано значение по умолчанию (= `BLANK_POINT`), которая представляет структуру типа `LocalPoint` из ТЗ, без `id`.

Далее чтобы создать вью `PointFormView` в режиме создания новой точки маршрута будет достаточно не указывать значение для `point`. Тогда он получит значение по умолчанию (= `BLANK_POINT`).

2023-02-01 05:48 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this._setState(PointFormView.parsePointToState(point));
В _этом_ случае просто хотел отделить блок инициализации значений полям объектам и вызова методов для действий с ними, чтобы таким образом упростить чтение, а в методах гарантированно работать с актуальными значениями полей.

2023-02-01 20:23 UTC, JuliaAf commented on src/view/point-form-view.js
>    constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
а почему из createTemplate нужно удалить BLANK_POINT?

2023-02-02 03:47 UTC, AlexMasterov commented on src/view/point-form-view.js
>    constructor({ point, destinations, offers, onFormSubmit, onRollupButtonClick }) {
Потому что он уже задается в конструкторе вью.

Если задать `BLANK_POINT` в `createTemplate`, которая находится в его модуле вью и им используется, то это будет означать исключительную ситуацию, что вью после своего создания, т.е. вызова конструктора, не имеет целостной структуры своего состояния.