6.7. Обновление века (часть 2)
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #12
Opened 2023-01-31 22:30 UTC by JuliaAf

2023-02-01 05:33 UTC, AlexMasterov requested changes

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
[Д8](https://up.htmlacademy.ru/ecmascript/19/criteries#d8)
> Методы внутри классов упорядочены

```
3. Основные методы класса
4. Обработчики событий [DOM]
5. Статические методы
```
Нужно проверить весь класс на этот критерий.

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>Проблема</summary>

```
abstract-stateful-view.js:48 Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')
```
</details>

Если раскрыть и свернуть форму редактирования, то выбрасывается исключение (ошибка).

Нужно разобраться и исправить.

`Б2`

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +        dateFormat: 'd/m/y H:i',
На защите проекта _могут_ придраться под разным критерием.

На всякий случай, используй `'d/m/y H:i'` через перечисление: (нужно добавить)

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/utils/points.js#L3-L6

~`Б5`, `Б31`

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      selectedOffers = selectedOffers.filter((id) => id !== +(offerId));
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L276
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L279
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L281
</details>

.filter((id) => id !== `+`(offerId))

> См. https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/11#discussion_r1091428194

Преобразование в число повторяется на каждой итерации цикла.

Лучше сразу и _один_ раз преобразуй в число.

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      offers: selectedOffers
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L279

В первом случае состояние с массивом предложений `this._state.offers` мутируется напрямую, что в некоторых случаях может быть (опасной) проблемой.

> Есть методы массива и техники, которые добавляют элемент в новую копию массива, не мутируя исходный

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L281

В втором случае создается новый массив.

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L284-L285

Актуально только для второго случая.

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    if (evt.target.hasAttribute('checked')) {
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L273
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L278
</details>

На защите _могут_ придраться.

[Д7](https://up.htmlacademy.ru/ecmascript/19/criteries#d7) 
> При использовании встроенного API, который поддерживает несколько вариантов использования, используется один способ

См. снова [Атрибуты и свойства](https://learn.javascript.ru/type-conversions) (и другие материалы по теме)

2023-02-01 05:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      dateFrom: userDate,
Сейчас сохранение выбранной даты в состояние вью происходит через _полное_ пересоздание объекта вью и `flatpickr`, используя `.updateElement()`. Но сохранить даты можно без полного пересоздания вью и перерисовки всей формы, просто используя `.setState()`, а для изменение настроек объектов `flatpickr`, например, `minDate` и `maxDate`, у них есть метод [`.set(option, value)`](https://flatpickr.js.org/instance-methods-properties-elements/#retrieving-the-flatpickr-instance:~:text=in%20most%20cases.-,set(option%2C%20value),-%23):
> Sets a config option optionto value, redrawing the calendar and updating the current view, if necessary

<details>
<summary>Пример</summary>

```js
#dateFromChangeHandler = ([userDate]) => {
  this.#datePickerTo.set('minDate', userDate);
  this._setState({ dateFrom: userDate });
}
```
Еще лучше:

```js
#dateFromChangeHandler = ([dateFrom]) => {
  this.#datePickerTo.set('minDate', dateFrom);
  this._setState({ dateFrom });
}
```
Другой обработчик можно доработать по аналогии

</details>

2023-02-01 14:23 UTC, JuliaAf commented on src/view/point-form-view.js
направишь на мысль?

2023-02-01 15:22 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>Проблема</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/presenter/point-presenter.js#L96-L99

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/presenter/point-presenter.js#L86-L87

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/framework/render.js#L67-L78
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/framework/render.js#L76-L76

После этого элемента больше нет в DOM.

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/view/point-form-view.js#L217-L218
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/framework/view/abstract-stateful-view.js#L21
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/framework/view/abstract-stateful-view.js#L41-L48

> Если вместо `.replaceChild` использовать `.replaceWith`, то ошибке не будет 😃
</details>

2023-02-01 15:24 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>presenter/point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/presenter/point-presenter.js#L96-L99
</details>

Попробуй эти действия выполнить в обратном порядке.

2023-02-01 15:30 UTC, AlexMasterov commented on src/view/point-form-view.js
Отчасти это проблема фреймворка:


<details>
<summary>framework/view/abstract-stateful-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6f75c2bbf5429aa1c90776754ec2cd42d89e6a8a/src/framework/view/abstract-stateful-view.js#L41-L51
</details>

<details>
<summary>fix</summary>


```js
#rerenderElement() {
  const oldElement = this.element;

  this.removeElement();

  oldElement.replaceWith(this.element);

  this._restoreHandlers();
}
```
</details>

2023-02-01 16:52 UTC, merged

2023-02-02 06:32 UTC, AlexMasterov commented on src/const.js
> +const DateFormat = {
const `Date`Format = {
  `DATE`: 'D MMM',
  TIME: 'HH:mm',
  `DATE`_FULL: 'd/m/y H:i',

Название ключей повторяют название самого перечисление.

```js
DateFormat.DATE
```

Нужно придумать название получше.

[`Б16`](https://up.htmlacademy.ru/ecmascript/19/criteries#b16) 
> Сложные составные константы собираются в перечисления `Enum`

2023-02-02 06:35 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    element.querySelector('#event-end-time-1').addEventListener('change', this.#dateToChangeHandler);
Обработчики уже заданы:

<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/ab3144761b8e6b118d39b59c5a99eca8d3003800/src/view/point-form-view.js#L260
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/ab3144761b8e6b118d39b59c5a99eca8d3003800/src/view/point-form-view.js#L274

</details>

> \+ для названия таких обработчиков используется глагол `handle`, но это можно оставить на усмотрение случайного проверяющего 

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/ab3144761b8e6b118d39b59c5a99eca8d3003800/src/view/point-form-view.js#L245-L246

В этом месте нужно удалить их добавление, чтобы не было повторных (лишних) перерисовок.

2023-02-02 06:36 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    if (evt.target.hasAttribute('checked')) {
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/ab3144761b8e6b118d39b59c5a99eca8d3003800/src/view/point-form-view.js#L302-L310
</details>

<details>
<summary>Пример</summary>

```js
const offerId = +evt.target.dataset.offerId;

const offers = evt.target.hasAttribute('checked')
  ? this._state.offers.concat(offerId)
  : this._state.offers.filter((id) => id !== offerId);

this._setState({ offers });
```
</details>