Module7 task1
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #13
Opened 2023-02-05 15:02 UTC by JuliaAf

2023-02-05 17:12 UTC, AlexMasterov requested changes

2023-02-05 17:12 UTC, AlexMasterov commented on src/const.js
> +  FULL: 'd/m/y H:i',
👍🏻

2023-02-05 17:12 UTC, AlexMasterov commented on src/model/offers-model.js
> +export default class OffersModel extends Observable {
`extends Observable`

Это лишние.

> Далее можешь вообще все данные получать и хранить в одной модели, _если тебе так будет проще_. Уже делай как тебе проще и что получается быстрее

2023-02-05 17:12 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +        isChecked: item.id === this.#currentSortType,
Исправила по своему 👍🏻

> В моем примере терялась `id`, тайно поправил только утром 😃

2023-02-05 17:12 UTC, AlexMasterov commented on src/main.js
> +  newPointButtonView.element.disabled = true;
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/main.js#L38
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/main.js#L43
</details>

newPointButtonView.element`.disabled = true`;

Прямая работа с элементом компонента нарушает его инкапсуляцию.

[Д26](https://up.htmlacademy.ru/ecmascript/19/criteries#d26) 
> Операции над DOM-элементами инкапсулированы

Для установки `disabled` нужно добавить вью методы или метод.

<details>
<summary>Примеры</summary>

```js
newPointButtonView.disable();
newPointButtonView.enable();
```
```js
newPointButtonView.setDisabled();
newPointButtonView.setEnabled();
```
```js
newPointButtonView.setDisabled(true);
````
</details>

2023-02-05 17:12 UTC, AlexMasterov commented on src/view/point-form-view.js
См.:
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/11#discussion_r1091435103
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/11#discussion_r1091436935

Нужно доработать в этом задание.

2023-02-05 17:12 UTC, AlexMasterov commented on src/view/point-form-view.js
См. ТЗ:
> Future — список запланированных точек маршрута, т. е. точек, у которых:

> **дата начала меньше текущей даты, а дата окончания — больше** (не сделано)
> дата начала события больше или равна текущей дате (сделано)

<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/utils/filter.js#L8-L10
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/utils/filter.js#L16-L18
</details>

Нужно доработать функции, добавив еще одну проверку.

2023-02-05 17:12 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.#handleDeleteClick(PointFormView.parseStateToPoint(this._state));
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/view/point-form-view.js#L250
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/view/point-form-view.js#L341-L343
</details>


Обработчик `handleDeleteClick` (= `onDeleteClick`) передается во вью только в случае редактирования точки маршрута, а в режиме создания его нет для `Cancel`.

Нужно лучше продумать и доработать обработку кнопки `.event__reset-btn`, которая имеет два режима: `Delete` и `Cancel`.

<details>
<summary>Проблема</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/view/point-form-view.js#L58

Если форма находится в режиме редактирования, то можно не добавлять обработчик на удаление или не вызывать его. Но с этим проблема, потому что значение режима до сих пор вычисляется внутри функции создания шаблона, а не при создании объекта состояния, как советовал ранее (для исправления нарушения принципа един. ответственности) и [показано в демо проект](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/master/src/view/task-edit-view.js#L296-L304).

Недоработки в прошлом сужают выбор нормальных решений.
</details>

Можно разделить обработку режимов, добавив еще один коллбэк для `cancelClick`. Можно просто проверить поле с обработчиком на возможность вызова: 

```js
this.#handleDeleteClick?.(...)
```

2023-02-05 17:12 UTC, AlexMasterov commented on src/presenter/points-presenter.js
>  export default class PointsPresenter {
[Д8](https://up.htmlacademy.ru/ecmascript/19/criteries#d8)
> Методы внутри классов упорядочены

```
3. Основные методы класса
4. Обработчики событий [DOM]
5. Статические методы
```
Нужно снова проверить весь класс на этот критерий.

2023-02-05 17:12 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +  #renderBoard() {
#render`Board`() {
#clear`Board`

В нашем проекте нет _доски_, а есть _список_.

Нужно просто удалить из названия.

2023-02-05 17:12 UTC, AlexMasterov commented on src/presenter/filter-presenter.js
>      return [
<details>
<summary>presenter/filter-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/presenter/filter-presenter.js#L25-L36
</details>

См.:

<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/presenter/points-presenter.js#L98
</details>

Нужно при создании данных для фильтров учесть актуальный `filterType`.

<details>
<summary>Пример</summary>

```js
const filterType = this.#filterModel.filter;

{ 
  type: FilterType.EVERYTHING, 
  isChecked: FilterType.EVERYTHING === filterType, 
  isDisabled: points.length === 0, 
}, 
```
</details>

2023-02-05 17:20 UTC, AlexMasterov commented on src/const.js
> если удалить все точки не удается вывести правильное сообщение

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/216834118-23d9484a-4104-4190-b23c-1176a720dce1.png)

</details>

Вроде работает, как и должно.

> На время открытия формы создания новой точки маршрута можно удалять сообщение и возвращать если новой точка не была создана (форму закрыли). Но это не требуется и некритично

2023-02-05 17:25 UTC, AlexMasterov commented on src/const.js
> +  FUTURE: 'There are no future events now',
> если удалить все точки не удается вывести правильное сообщение


```diff
- FUTURE: 'There are no future events now',
+ [FilterType.FUTURE]: 'There are no future events now',
```

2023-02-05 17:54 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.#handleDeleteClick(PointFormView.parseStateToPoint(this._state));
<details>
<summary>presenter/new-point-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-big-trip-simple-19/blob/88eeb5ad224b1829f8806bf21cce9886b1a0ac8b/src/presenter/new-point-presenter.js#L15
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/presenter/new-point-presenter.js#L25
</details>

```js
this.#handleResetClick // undefined
```
🤔

2023-02-05 18:38 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.#handleDeleteClick(PointFormView.parseStateToPoint(this._state));
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/presenter/new-point-presenter.js#L25

Поля для обработчика с названием `onResetClick` нет:

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/eb627121f0e160ec17ad44e20be2270e85ec1292/src/view/point-form-view.js#L201

2023-02-05 18:46 UTC, JuliaAf commented on src/view/point-form-view.js
имеешь ввиду, что надо добавить проверку для everything?

2023-02-05 18:50 UTC, AlexMasterov commented on src/view/point-form-view.js
Имею ввиду именно то, что написал:

> Нужно доработать функции [в спойлере], добавив еще одну проверку

> дата начала меньше текущей даты, а дата окончания — больше (не сделано)

2023-02-05 21:33 UTC, AlexMasterov requested changes
Нужно немного доработать и можно двигаться дальше.

2023-02-05 21:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    element.querySelector('.event__input--price').addEventListener('input', this.#priceInputHandler);
Лучше `change`.

2023-02-05 21:33 UTC, AlexMasterov commented on src/view/point-view.js
> +        <time class="event__date" datetime="${ dateFrom }">${ pointDate }</time>
На этом место не было замечаний и здесь всё _было_ нормально.

> Теперь разметка стала _невалидной_

Значением `datetime` должна быть дата в формате ISO. Про это рассказывал на консультации и давал ссылки на спецификацию и тренежер Академии.

2023-02-05 21:33 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      basePrice: evt.target.value,
Теперь в модель сохраняется неправильная структура `Point`.

Какой тип у значения evt.target`.value`, а какой тип [был] у `basePrice`?

2023-02-05 21:33 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +      onCancelClick: this.#handleCancelClick,
В этом презентере метод `this.#handleCancelClick` _никогда_ не будет вызван = мертвый код.

2023-02-05 21:33 UTC, AlexMasterov commented on src/utils/filter.js
> +  return points.some(({ dateFrom, dateTo }) => dateFrom.getTime() >= dateNow || (dateFrom.getTime() < dateNow && dateTo.getTime() > dateNow));
<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/f97b42866e1bbec7ab736da34cd624ccb03491d7/src/utils/filter.js#L9
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/f97b42866e1bbec7ab736da34cd624ccb03491d7/src/utils/filter.js#L17
</details>

Могут придраться из-за дублирования.

<details>
<summary>Варианты</summary>

```js
const checkPointByFuture = ({ dateFrom, dateTo }, dateNow) =>
    dateFrom.getTime() >= dateNow ||
    (dateFrom.getTime() < dateNow && dateTo.getTime() > dateNow);

points.some((point) => checkPointByFuture(point, dateNow))
```

```js
const makeCheckerByFuture = (dateNow) =>
  ({ dateFrom, dateTo }) => dateFrom.getTime() >= dateNow || (dateFrom.getTime() < dateNow && dateTo.getTime() > dateNow);

points.some(makeCheckerByFuture(dateNow))
```

</details>

2023-02-05 21:33 UTC, AlexMasterov commented on src/const.js
> +  FUTURE: 'FUTURE',
Таким образом перечисление _подгоняется_ под один независимый случай, в котором оно используется, а должно быть наоборот.

2023-02-05 21:45 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    this.#filterModel.setFilter(UpdateType.MAJOR, this.#filterType);
Нужно вернуть, как было.

2023-02-05 21:55 UTC, AlexMasterov commented on src/const.js
> эта ошибка возникает, когда пытаешься сохранить новую точку, и когда в точке выбираешь дату

См. https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/12#discussion_r1094099877.

2023-02-05 22:26 UTC, JuliaAf commented on src/view/point-view.js
> +        <time class="event__date" datetime="${ dateFrom }">${ pointDate }</time>
забыла вернуть на место

2023-02-05 22:32 UTC, JuliaAf commented on src/const.js
странно, не видела это замечание...

2023-02-06 11:05 UTC, AlexMasterov commented on src/presenter/new-point-presenter.js
> +      { ...point },
```diff
- { ...point },
+ point,
```

2023-02-06 11:30 UTC, AlexMasterov approved these changes
Пожалуйста, мелкие замечания в остатке исправь при выполнении следующего задания.

2023-02-06 11:30 UTC, AlexMasterov commented on src/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/216959523-c057ed32-50b6-4585-88b4-26ecbf74aab9.png)

</details>

Если открыть форму редактирования и не закрывая, открыть форму создания, то на `document` остается обработчик для `keydown` от формы редактирования. Обработчики могут накапливаться.


<details>
<summary>Проблема 2</summary>

![image](https://user-images.githubusercontent.com/700213/216959655-1308c858-152f-4492-ae94-d1fce8d3b857.png)

</details>

Если открыть форму редактирования и не закрывая, сменить фильтр, то на `document` остается обработчик для `keydown` от формы редактирования. Обработчики могут накапливаться.

Нужно разобраться и исправить.

[`Б36`](https://up.htmlacademy.ru/ecmascript/19/criteries#b36) 
> Обработчики события добавляются и удаляются своевременно

2023-02-06 11:30 UTC, AlexMasterov commented on src/model/filter-model.js
> +  #filter = null;
```diff
- #filter = null;
+ #filter = '';
```

2023-02-06 11:30 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      basePrice: +evt.target.value,
У DOM-элемента поля с типом `number` есть свойство, которое сразу возвращает _числовое_ значение:

 
```diff
- basePrice: Number(evt.target.value)
+ basePrice: evt.target.valueAsNumber
```

2023-02-06 11:30 UTC, merged