1.11. Время разбивать камни
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #3
Opened 2022-12-08 21:30 UTC by JuliaAf

2022-12-08 22:56 UTC, AlexMasterov requested changes

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/loading-view.js
> +  return '<p class="trip-events__msg">Loading...</p>';
<details>
<summary>markup/loading.html</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/6674293074aa07bc36db8216ecb239611976aaa2/markup/loading.html#L54
</details>


<details>
<summary>markup/list-empty.html</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/markup/list-empty.html#L54
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/src/view/no-points-description-view.js#L4
</details>

Разметка отличается только сообщением.

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/filter-container-view.js
> +function filterContainerTemplate() {
Другие подобные функции для создания разметки начинаются с глагола `create`, а здесь это единообразие в именование нарушено.

[`Б 10`](https://up.htmlacademy.ru/ecmascript/19/criteries#b10)
> Название функции или метода должно быть глаголом и соответствовать действию, которое выполняет функция или метод

С учетом нахождения таких функций в модуле с компонентом их название можно упростить:

```diff
- function filterContainerTemplate() {
+ function createTemplate() {
```

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/main-container-view.js
> +function mainContainerTemplate() {
Нужно в название функции добавить глагол, который уже используется для других похожих функций.

Б10

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/point-event-view.js
> +export default class PointView {
view/`point-event-view`.js !== `PointView`

[`Б 27`](https://up.htmlacademy.ru/ecmascript/19/criteries#b27)
> если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/point-event-view.js
> +  return (` <div class="event">
В таком использование `()` нет смысла.

Для сохранения отступа начала и конца разметки нужно правильно использовать `()`:
```js
return (
  `<div class="event">
```
> Важно помнить, что шаблонный строки сохраняют пробелы и переводы строки. На основе разметки с пустой строкой в начале будет создан узел типа `#text` (а не `Element`), который нам не нужен. Желательно этого не допускать. См. [пример проблемы](https://developer.mozilla.org/ru/docs/Web/API/Node/firstChild#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80)

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/point-view.js
> +  return ('<li class="trip-events__item"></li>'
В таком использование `()` нет смысла.

2022-12-08 22:56 UTC, AlexMasterov commented on src/view/sort-view.js
> +  return (`<form class="trip-events__trip-sort  trip-sort" action="#" method="get">
В таком использование `()` нет смысла.

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +  constructor ({pointsContainer}) {
<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/src/presenter/points-presenter.js#L15
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/src/presenter/points-presenter.js#L22-L23
</details>


Название основного элемента-контейнера можно упростить:
```diff
- constructor ({pointsContainer}) {
+ constructor ({container}) {
```
Если будет изменено название класса, то не придется менять название параметра.

> Если в классе появится еще один контейнер, то уже его имя можно уточнить

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    render (this.pointsList, this.pointsContainer);
Обращаю внимание, что `this.pointsContainer` указывает на элемент, который добавлен в DOM и в нем отображается.

<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/src/presenter/points-presenter.js#L28-L43
</details>

[`Б 35`](https://up.htmlacademy.ru/ecmascript/19/criteries#b35)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +      if(i === 0){
Не стоит нагружать такой проверкой весь цикл. Форму можно просто добавить вне цикла.

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    render (new NoPointsDescriptionView(), this.pointsContainer);
Компоненты `LoadingView`, `NoPointsDescriptionView` рендерить не нужно. На текущем этапе достаточно их создания.

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/filter-presenter.js
> +  mainContainer = new MainContainer();
Это лишние и нужно удалить.

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +  init() {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/206581374-2c13bc18-d0c6-45ab-b7c7-f781eb9fa302.png)

</details>

Это форма _создания_ точки маршрута.

См. задание:
> компонент «Форма редактирования» отрисовывается 1 раз, но должен располагаться первым в списке

2022-12-08 22:56 UTC, AlexMasterov commented on src/main.js
> +
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/public/index.html#L33

Для этой разметки желательно тоже создать компонент.

> После создания компонента нужно не забыть удалить её разметку из `index.html`

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/filter-presenter.js
> +import { render } from '../render.js';
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/c64559dc324dc37f7614184d9aa16646f5c5782e/src/render.js#L9

const new`Element` = document.createElement('div'); 

Нужно из названия переменной удалить суффикс `Element` или использовать его во всём проекте, для всех переменных, который указывают на DOM-элементы.

[`Д 6`](https://up.htmlacademy.ru/ecmascript/19/criteries#d6) 
> Используется единый стиль именования переменных

> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, то это правило работает везде

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +        render (new PointDestinationView(), this.pointDetails.getElement());
Предупреждаю, что в демо проекте не будет показано удобного решения для автоматической сборки (композиции) элементов компонентов, чтобы соблюдать общею целостность при обновление род. и доч. элементов, не допускать утечек памяти и прочего.

Заниматься подобным вручную, без должного знания и опыта может быть сложно.

2022-12-08 22:56 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +      render (this.pointsItem, this.pointsList.getElement());
Один и тот же элемент компонента ренедриться на каждой итерации цикла.

Нужно выполнить рендер вне цикла, _один_ раз.

2022-12-09 11:49 UTC, JuliaAf commented on src/view/point-event-view.js
> +  return (` <div class="event">
👍

2022-12-15 20:49 UTC, merged