2.15. Шаблонизируй это
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #4
Opened 2022-12-20 20:12 UTC by JuliaAf

2022-12-20 21:31 UTC, AlexMasterov requested changes

2022-12-20 21:31 UTC, AlexMasterov commented on src/main.js
>  const container = document.querySelector('.trip-events');
```diff
- const container = document.querySelector('.trip-events');
+ const tripEventsContainer = document.querySelector('.trip-events');
```
> Обсуждалось и исправлялось на консультации

2022-12-20 21:31 UTC, AlexMasterov commented on src/model/points-model.js
> +  offers = getOffers();
Желательно для данных с `destinations` и `offers` создать отдельные модели.

2022-12-20 21:31 UTC, AlexMasterov commented on src/presenter/header-presenter.js
>    headerContainer = document.querySelector('.trip-controls__filters');
headerContainer = `document.querySelector('.trip-controls__filters')`;

В классах подобной прямой работы с DOM быть не должно.

Нужно передавать _такой_ DOM-элемент в конструктор, как основной `container`.

<details>
<summary>presenter/header-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/presenter/header-presenter.js#L13-L14
</details>

`HeaderPresenter` переделай в `FilterPresenter`, а с `NewEventButtonView` пока (?) работой в `main.js`.

> _Хотел_ про это сказать на консультации~

2022-12-20 21:31 UTC, AlexMasterov commented on src/presenter/points-presenter.js
>      for (let i = 0; i < this.points.length; i++) {
<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/presenter/points-presenter.js#L23-L39
</details>

В цикле `for` значение инкремента `i`, _по сути_, используется только для обращение к массиву `this.points`.

Нужно переписать цикл `for` на `for of` (или `.forEach`).

[`Д 20`](https://up.htmlacademy.ru/ecmascript/19/criteries#d20)
>  Там, где не требуется индекс элемента массива или нужно обойти все элементы итерируемой структуры данных, используется цикл `for .. of` вместо цикла `for`

[`Д 24`](https://up.htmlacademy.ru/ecmascript/19/criteries#d24) 
> Для работы с JS-коллекциями используются итераторы для массивов

2022-12-20 21:31 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +        const pointFormView = new PointFormView({
<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/presenter/points-presenter.js#L24-L31
</details>

`if(i === 0) {`

Рендерить `PointFormView` лучше _до цикла_ или, в крайнем случае, _после него_.

> Обсуждалось на консультации

2022-12-20 21:31 UTC, AlexMasterov commented on src/render.js
> +function createElement(template) { //зачем создавать контейнер, класть туда template, и в итоге его же и отдавать
> зачем создавать контейнер, класть туда template, и в итоге его же и отдавать

Это один из популярных способов создания DOM-элемента из разметки.

> Попробуй сделать это иначе 😃

2022-12-20 21:31 UTC, AlexMasterov commented on src/utils.js
>  const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
const getRandomArray`Element` = (`items`) => `items`[Math.floor(Math.random() * `items`.length)];

```diff
- const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
+ const getRandomArrayItem = (items) => items[Math.floor(Math.random() * items.length)];
```

\+

const getRandomArrayElement = (items) `=>` items[Math.floor(Math.random() * items.length)];

[`Д 5`](https://up.htmlacademy.ru/ecmascript/19/criteries#d5) (Обновлён 09.12.22)
> по умолчанию используется _декларативное_ объявление функций

2022-12-20 21:31 UTC, AlexMasterov commented on src/utils.js
> +function formatDateLong(date) {
`formatDateLong`

Не нахожу в проекте применение этой функции.

[`Б 18`](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, **которые не используются**, включая закомментированные участки кода.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      <label class="event__type-label  event__type-label--${type.toLowerCase()}" for="event-type-${type.toLowerCase()}-1">${type}</label>
**4x** type.`toLowerCase()`

<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/point-form-view.js#L46-L56
</details>

Лучше записать название типов в нижним регистре.

> См. также https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/4#discussion_r1053752028 (hint)

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +// function createofferOptionsTemplate ({ title, price, id }) {
`//`

Нужно удалить.

[`Б 18`](https://up.htmlacademy.ru/ecmascript/19/criteries#b18) 
> В коде проекта нет файлов и частей кода, которые не используются, **включая закомментированные участки кода**

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/point-form-view.js#L41-L56
</details>

[`Д 17`](https://up.htmlacademy.ru/ecmascript/19/criteries#d17) 
> **Константы**, используемые внутри функций, **создаются вне функций** и используются повторно через замыкания

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  // const offerOptionsTemplate = offerOptions.map(createofferOptionsTemplate).join('');
`//`

Нужно удалить.

Б18

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  const typeListItems = TYPES.map(createTypeListItemTemplate).join('');
`typeListItems`

Это строка с разметкой _шаблона_.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    destination: pointDestinationId,
Для [малого и узкого контекста] этой функции добавление `point` в название переменных избыточно.

> Можно спорить

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  const TYPES = [
`TYPES` чего?

Нужно уточнить.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    DELETE: 'Delete',
const `Cancel`ButtonText = {
  `CANCEL`: 'Cancel',
  DELETE: 'Delete',

Неудачное название перечисления. 

<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/point-form-view.js#L146-L148
</details>


Лучше так:

```diff
- const CancelButtonText = {
+ const ResetButtonText = {
```

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
> +        <label class="event__offer-label" for="event-offer-luggage-${id}">
id="event-offer-`luggage`-${id}"
name="event-offer-`luggage`"
for="event-offer-`luggage`-${id}"

Желательно использовать значение из данных или вообще убрать, оставив для уникальности только `id`.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
См. задание:
> Обратите внимание, если у вас форма редактирования выступает и в роли формы создания — вы решили обойтись одним компонентом, [как в демо-проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-3/src/view/task-edit-view.js#L147) — **нужно предусмотреть, чтобы шаблон корректно отображался с «пустыми» данными**

См. ТЗ:
> Если информация о пункте назначения отсутствует, **блок «Destination» не отображается**

> Список дополнительных опций доступен не для всех типов точек маршрута. Для некоторых типов точек дополнительные опции могут отсутствовать. **В этом случае контейнер для вывода дополнительных опций не отображается**

Нужно постараться доработать с этом задание.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/208766971-2b1a2bbc-42a5-4f27-81c5-1f00e7783cee.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/208767046-73cb7135-0e42-4929-82f8-b4c1a5236175.png)

</details>

Нужно, как в макете, доработать отображение выбранного [в данных] типа точки маршрута.

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/point-form-view.js
>            <div class="event__field-group  event__field-group--price">
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/208767654-ab69d85b-28d9-4b81-8df4-54f219315964.png)

</details>

Нужно использовать значение базовой стоимости из данных.

> См. пример в макете

2022-12-20 21:31 UTC, AlexMasterov commented on src/main.js
[`Б 17`](https://up.htmlacademy.ru/ecmascript/19/criteries#b17) 
> Приватные и защищённые поля в классах **помечены** и не используются снаружи

Нужно учесть в классах следующих модулях:

`model/points-model.js`
`presenter/header-presenter.js`
`presenter/points-presenter.js`

> На `view` с `this.element` можно не тратить время. Далее этот общих код будет заменен базовым классом

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/sort-view.js
> +      </div>
<details>
<summary>view/sort-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/sort-view.js#L6-L29
</details>

checked`=""`
disabled`=""`

Подобного нет в разметки макета.

Это синтаксис [`XHTML`](https://ru.wikipedia.org/wiki/XHTML):
> Развитие XHTML остановлено; новые версии XHTML не выпускаются; **рекомендуется использовать HTML**

2022-12-20 21:31 UTC, AlexMasterov commented on src/view/trip-message-view.js
> +  #message = 'Click New Event to create your first point';
```diff
- #message = 'Click New Event to create your first point';
+ #message = '';
```

<details>
<summary>markup</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/markup/loading.html#L54
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/markup/list-empty.html#L54
</details>

Для этих строк сразу создай _перечисление_, а для самого перечисления отдельный модуль, например, `const.js`.

<details>
<summary>markup</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/markup/list-empty.html#L58-L60
</details>

Для этих строк советую тоже создать _отдельное_ перечисление.

2022-12-20 21:41 UTC, AlexMasterov commented on src/view/point-view.js
<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/208772151-c988c84e-d1a1-409d-b55d-27b649f360e6.png)

</details>

В случае отсутствие выбранных предложений больше не отображается `No additional offers`.

Нужно вернуть, как это показано в макете.

2022-12-20 21:46 UTC, AlexMasterov commented on src/view/sort-view.js
> +      </div>
<details>
<summary>view/sort-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/sort-view.js#L6-L29
</details>

Разметку дублируется.

Попробуй сократить с помощью _интерфейса_ функции:
```js
createSortItemTemplate({ id: 'day', title: 'Day', checked: true })
createSortItemTemplate({ id: 'event', title: 'Event', disabled: true })
```

2022-12-21 11:25 UTC, JuliaAf commented on src/presenter/points-presenter.js
>      for (let i = 0; i < this.points.length; i++) {
i здесь используется еще и для того, чтобы первым элементом отрисовалась форма. еще я не учла, что у меня форма и первый point - одинаковые. поэтому пришлось ввести еще условие   if(i > 0) для точек маршрута

2022-12-21 11:49 UTC, JuliaAf commented on src/render.js
> +function createElement(template) { //зачем создавать контейнер, класть туда template, и в итоге его же и отдавать
🤔

2022-12-21 11:52 UTC, JuliaAf commented on src/utils.js
>  const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
почему в removeElement, createElement и getElement можно использовать слово элемент?

2022-12-21 12:10 UTC, JuliaAf commented on src/view/point-form-view.js
> +    destination: pointDestinationId,
сделано для более читабельного вида, т.к. слова id, type, destination встречаются повсюду

2022-12-21 12:15 UTC, AlexMasterov commented on src/utils.js
>  const getRandomArrayElement = (items) => items[Math.floor(Math.random() * items.length)];
> почему в removeElement, createElement и getElement можно использовать слово элемент?

Никто не запрещает, тем более в классе `element` указывает на DOM-элемент, а не элемент массива.

В случае функции `getRandomArrayElement`, её название обещает вернуть `Element`. Но из чего? из параметра `items`. Но почему не из `elements`? (так было раньше, на прошлых интенсивах)

Скорее всего потому, что эта функция [заимствована из демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-3/src/utils.js#L5-L7). Наставники давно просили авторов определиться с (абстрактным) именованием элементов массивов, в пользу `items` вместо `elements`, потому что при работе в окружение браузера, `elements` может указывать на DOM-элемент, что может создать путаницу. Но авторы курса не до конца исправили функцию, а студенты просто заимствуют, как есть, не задаваясь подобным вопросами.

2022-12-21 12:34 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    destination: pointDestinationId,
Если приходиться подобным образом уточнять названия переменных функции, то это может указывать на проблему, что функция работает сразу с несколькими (семантическими) контекстами. Подобное считается "запахом кода".

На консультации, показывая, как можно быстро разрешить конфликт имен (через переименование `destination: destinationId`), так же указывал на эту проблему. Тогда советовал создать функцию, которая будет работать только с данными по направлению, не смешиваясь с остальными.

2022-12-21 12:37 UTC, JuliaAf commented on src/main.js
я приватные поля еще не делала (только то, что ты мне показывал), они будут в след. задании

2022-12-21 12:41 UTC, AlexMasterov commented on src/main.js
Сначала хотел отложить до след. задания, но увидел, что в некоторых классах они уже используются.

> только то, что ты мне показывал

Получается, что так 😃

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/e26e2c4684f66c0cf6ea44a8f3709e1b75ba1122/src/view/point-form-view.js#L179-L181

2022-12-21 21:37 UTC, AlexMasterov requested changes
К сожалению, нужно немного доработать.

2022-12-21 21:37 UTC, AlexMasterov commented on src/const.js
> +  ALL: 'Click New Event to create your first point',
<details>
<summary>const.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/const.js#L17
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/const.js#L24
</details>

Сообщения дублируются.

```diff
- ALL: 'Click New Event to create your first point',
+ ALL: TripMessageText.NO_POINTS,
```

2022-12-21 21:37 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +        point: point,
ES6+
```diff
-  point: point,
+  point,
```

2022-12-21 21:37 UTC, AlexMasterov commented on src/utils.js
> +const capitalize = (string) => string.charAt(0).toUpperCase() + string.slice(1);
const capitalize = (`string`) => `string`.charAt(0).toUpperCase() + `string`.slice(1);

[`Б 9`](https://up.htmlacademy.ru/ecmascript/19/criteries#b9) 
> В названии переменных не используется тип данных (= `string`)

<details>
<summary>Пример</summary>

```diff
- const capitalize = (string) => string.charAt(0).toUpperCase() + string.slice(1);
+ const capitalize = (text) => text.charAt(0).toUpperCase().concat(text.slice(1));
```
</details>

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +const BLANK_POINT = {
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L5-L12
</details>

Нужно исправить:

```js
const DEFAULT_POINT_TYPE = POINT_TYPES[0];

const BLANK_POINT = {
  type: DEFAULT_POINT_TYPE,
  dateFrom: null,
  dateTo: null,
  destination: 0,
  basePrice: 0,
  offers: [],
};
```

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  const offersTemplate = offerOptions === undefined ? '' :
`offerOptions === undefined`

> Почему в компонентах у данных могут быть `undefined` 🤔

[`Д 10`](https://up.htmlacademy.ru/ecmascript/19/criteries#d10) 
> В проекте не должно быть избыточных проверок

<details>
<summary>Пример</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L46

```diff
- const { offers: offerOptions } = offers.find(({ type }) => type === pointType); 
+ const { offers: offerOptions = [] } = offers.find(({ type }) => type === pointType); 
```

или

```diff
- const { offers: offerOptions } = offers.find(({ type }) => type === pointType); 
+ const { offers: offerOptions } = offers.find(({ type }) => type === pointType) ?? []; 
```

```diff
- const offersTemplate = offerOptions === undefined ? '' :
+ const offersTemplate = offerOptions.length === 0 ? '' :
```
</details>

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +        ${offerOptionsTemplate}
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L71-L83
</details>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L85

Если сработает условие, то преждевременное создание `offerOptionsTemplate` окажется избыточным.

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +          ${destinationPicturesTemplate}
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L93

Если сработает условие, то преждевременное создание `destinationPicturesTemplate` окажется избыточным.

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-view.js
> +  const offerOptionsTemplate = offerOptions === undefined ? NO_SELECTED_OFFERS : offerOptions.map(createofferOptionsTemplate).join('');
`offerOptions === undefined`

[`Д 10`](https://up.htmlacademy.ru/ecmascript/19/criteries#d10) 
> В проекте не должно быть избыточных проверок

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/sort-view.js
> +      ${createSortItemTemplate({ id: 'event', title: 'Event', disabled: 'disabled' })}
Почему `checked` и `disabled` _строка_? (это плохой интерфейс) 🤔

Их название указывает на булево значение, как и было [показано в моем примере](https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/4#discussion_r1053780623).

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/trip-message-view.js
> +  #message = 'Click New Event to create your first point';
В этом месте не исправлено.
```diff
- #message = 'Click New Event to create your first point';
+ #message = '';
```

2022-12-21 21:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  const isNew = pointId === undefined;
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/a668a1157f845e955b9ec826dfc9f1ba3edf3d81/src/view/point-form-view.js#L35

```diff
- id: pointId,
+ id: pointId = '',
```

Ну хотя бы так:
```diff
- const isNew = pointId === undefined;
+ const isNew = pointId === '';
```

2022-12-21 21:37 UTC, AlexMasterov commented on src/const.js
> +const COUNT = 3;
`COUNT` чего?

> Это корневой модуль `const.js`, который используется во всем проекте. Старайся уточнять названия

Лучше сразу удалить, а в модели просто задай число.

2022-12-21 21:37 UTC, AlexMasterov commented on src/const.js
> +const NO_SELECTED_OFFERS = 'No additional offers';
Нужно вернуть в модуль непосредственного использования

```diff
- const NO_SELECTED_OFFERS = 'No additional offers';
+ const NO_SELECTED_OFFERS_TEXT = 'No additional offers';
```
> Предвидя подобные переносы, `ResetButtonText` попросил оставить в модуле, где он уместен и используется 😟

2022-12-21 22:54 UTC, AlexMasterov commented on src/view/point-form-view.js
> +const BLANK_POINT = {
Нужно добавить:
```js
isFavorite: false,
```

2022-12-22 12:42 UTC, AlexMasterov commented on src/view/point-form-view.js
> +const BLANK_POINT = {
> Нужно добавить:
> 
> ```js
> isFavorite: false,
> ```

Это не нужно 😄

Оказывается, что добавления в избранное нет в простой версии ТЗ.

2022-12-22 14:13 UTC, AlexMasterov commented
[LGTM](https://coub.com/view/29wef6)

2022-12-22 14:14 UTC, merged