3.10. Революция или эволюция? (часть 1)
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #5
Opened 2022-12-22 22:08 UTC by JuliaAf

2022-12-22 22:24 UTC, AlexMasterov requested changes

2022-12-22 22:24 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +      if (evt.key === 'Escape' || evt.key === 'Esc') {
```diff
- if (evt.key === 'Escape' || evt.key === 'Esc') {
+ if (evt.key.startsWith('Esc')) {
```

2022-12-22 22:24 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    const pointComponent = new PointView({
Желательно определиться с именованием для всего проекта:

```diff
- const pointComponent = new PointView({
+ const pointView = new PointView({
```

2022-12-22 22:24 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +      this.#pointsListView.elementreplaceChild(pointComponent.element, pointFormComponent.element);
Прошу проверять работу перед отправкой:
```diff
- this.#pointsListView.elementreplaceChild(pointComponent.element, pointFormComponent.element);
+ this.#pointsListView.element.replaceChild(pointComponent.element, pointFormComponent.element);
```

2022-12-22 22:33 UTC, AlexMasterov commented on src/presenter/points-presenter.js
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/fbbc95effaf14957a6c3b2fbb27b3efe946904c7/src/view/point-form-view.js#L6-L13

Нужно исправить объявления объекта, название полей, как показано в моем примере: https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/4#discussion_r1054839019.

2022-12-22 22:37 UTC, AlexMasterov commented on src/presenter/points-presenter.js
```
point-form-view.js:45 Uncaught TypeError: Cannot destructure property 'name' of 'destinations.find(...)' as it is undefined.
```
Если открыть форму с `BLANK_POINT`, то возникает ошибка.

Нужно обработать отсутствие `destination`.

2022-12-22 22:51 UTC, AlexMasterov commented on src/presenter/points-presenter.js
У формы создания новой точки маршрута нет кнопки для сворачивания, а сейчас на неё добавляется обработчик. Эту ситуацию потребуется обработать, когда добавление обработчиков будет происходить через методы компонентов.

Поэтому пока можно отложить.

2022-12-23 03:01 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
const replacePointToForm = `() =>` {

Д5

2022-12-23 14:59 UTC, JuliaAf commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
на ретро Игорь сказал, что этот критерий обновили, теперь можно использовать как стрелки так и декларативные ф-ии

2022-12-23 15:54 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
Прочти внимательно описание критерия.

2022-12-23 16:02 UTC, JuliaAf commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
"Например, по умолчанию используется декларативное объявление функций, а стрелочные функции применяются в качестве обработчиков событий, чтобы не терять контекст.", и в демо-проекте стрелочные показаны, а по всему остальному коду декларативные ¯\_(ツ)_/¯

2022-12-23 16:15 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
Думаю, что случайный проверяющий на защите с легкостью разберётся с этим критерием.

В любом случае, стоимость исправления определений функций минимальна. Лучше сделать фокус на другом.

2022-12-23 16:21 UTC, JuliaAf commented on src/presenter/points-presenter.js
> +    const replacePointToForm = () => {
ладно уговорил😁

2022-12-23 20:13 UTC, JuliaAf commented on src/presenter/points-presenter.js
_>Если информация о пункте назначения отсутствует, блок «Destination» не отображается_
 а что под этим подразумевается?  что  в destinations  не существует нужного id? или что id есть, но больше никакой информации о пункте назначения нет?

2022-12-23 21:07 UTC, AlexMasterov commented on src/presenter/points-presenter.js
Набросал ответ в чате. 

> TL;DR: _It depends._ На твой выбор 😃

2022-12-28 05:04 UTC, AlexMasterov approved these changes

2022-12-28 05:04 UTC, AlexMasterov commented on src/view/point-form-view.js
> +        <p class="event__destination-description">${ description ?? '' }</p>
description `?? ''`

Это лишние.

2022-12-28 05:04 UTC, AlexMasterov commented on src/view/point-form-view.js
> +            <input class="event__input  event__input--destination" id="event-destination-1" type="text" name="event-destination" value="${ destinationName ?? '' }" list="destination-list-1">
destinationName `?? ''`

Это лишние.

2022-12-28 05:04 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    pictures = []
name: destinationName `= ''`,

Это лишние.

2022-12-28 05:04 UTC, AlexMasterov commented on src/view/point-form-view.js
> +  const { offers: offerOptions = [] } = offers.find(({ type }) => type === pointType) ?? BLANK_OFFER;
offers: offerOptions `= []`

Это лишние.

2022-12-28 05:04 UTC, merged