4.15. Разделяй и властвуй
htmlacademy-ecmascript/123003-big-trip-simple-19 pull request #7
Opened 2023-01-04 14:45 UTC by JuliaAf

2023-01-04 15:09 UTC, AlexMasterov requested changes

2023-01-04 15:09 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#rollupButtonClickHandler);
Форма создания новой точки не отображается.

Если `this.point` указывает на структуру `BLANK_POINT`, то выбрасывается исключение (ошибка):

```
point-form-view.js:200 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
```

Нужно разобраться и исправить.

Б2

2023-01-04 15:09 UTC, AlexMasterov commented on src/presenter/points-presenter.js
>          document.removeEventListener('keydown', escKeyDownHandler);
<details>
<summary>presenter/points-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/presenter/points-presenter.js#L50-L51
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/presenter/points-presenter.js#L54-L55
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/presenter/points-presenter.js#L68-L69
</details>

[Д11.](https://up.htmlacademy.ru/ecmascript/19/criteries#d11) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий.

2023-01-04 15:09 UTC, AlexMasterov commented on src/presenter/points-presenter.js
>      render(pointFormView, this.#pointsListView.element);
```diff
- render(pointFormView, this.#pointsListView.element);
+ render(pointView, this.#pointsListView.element);
```

2023-01-04 15:09 UTC, AlexMasterov commented on src/utils/points.js
> +export { formatDateShort, formatTime, capitalize };
`capitalize` в `common.js`

2023-01-04 15:09 UTC, AlexMasterov commented on src/utils/common.js
> +export { getRandomArrayItem };
`getRandomArrayItem` в `mock/mock.js` / `mock/random.js`

> Скоро потребуется удалить _временный_ код, что проще сделать, когда он в одном месте

2023-01-04 15:09 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    if (this.element.querySelector('.event__rollup-btn') !== null) {
В каком случае может пропасть кнопка?

2023-01-04 15:09 UTC, AlexMasterov commented on src/view/point-view.js
> +    if (this.element.querySelector('.event__rollup-btn') !== null) {
В каком случае может пропасть кнопка?

2023-01-04 15:09 UTC, AlexMasterov commented on src/view/point-form-view.js
> +export default class PointFormView extends AbstractView {
[Д8.](https://up.htmlacademy.ru/ecmascript/19/criteries#d8) 
> Методы внутри классов упорядочены

```
2. Геттеры и сеттеры свойств класса
4. Обработчики событий
```

2023-01-04 15:09 UTC, AlexMasterov commented on src/view/point-view.js
> +export default class PointView extends AbstractView {
[Д8.](https://up.htmlacademy.ru/ecmascript/19/criteries#d8) 
> Методы внутри классов упорядочены

```
2. Геттеры и сеттеры свойств класса
4. Обработчики событий
```

2023-01-04 15:09 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/filter-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/view/filter-view.js#L6-L9
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/view/filter-view.js#L11-L14
</details>

Разметка с фильтрами почти полностью дублируется, отличаясь только значениями некоторых атрибутов.

Советую для создания разметки `.trip-filters__filter` тоже написать функцию, например, с таким интерфейсом:

```js
createFilterTemplate({ id: 'everything', title: 'Everything', isChecked: true })
createFilterTemplate({ id: 'future', title: 'Future' })
```
> См. пример в `view/sort-view.js`

Нам это поможет далее при реализации фильтрации

2023-01-04 15:15 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#rollupButtonClickHandler);
https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/view/point-form-view.js#L199-L200

Пожалуйста, этот код с добавлением обработчиков отдели пустой строкой от кода выше, чтобы упростить чтение.

2023-01-04 15:30 UTC, AlexMasterov commented on src/view/point-form-view.js
<details>
<summary>view/point-form-view.js</summary>

https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/blob/49ba06ba8efad9e87d60780fa591e6c2c0d54eaa/src/view/point-form-view.js#L42-L183
</details>

> В продолжение https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/4#discussion_r1054338481

<details>
<summary>Принцип единственной ответственности</summary>

![image](https://user-images.githubusercontent.com/700213/210588973-a91a7160-1381-40d4-b485-14576d70ae87.png)

</details>

Сейчас у функции `createTemplate` несколько независимых причин для изменения: структуры (и работа с ними) и разметка.

2023-01-04 20:43 UTC, JuliaAf commented on src/view/point-form-view.js
> +    if (this.element.querySelector('.event__rollup-btn') !== null) {
если это форма создания новой точки, то кнопки не будет http://joxi.ru/82QEnbjU8EKWb2

2023-01-04 21:21 UTC, JuliaAf commented on src/view/point-form-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#rollupButtonClickHandler);
эта ошибка связана с https://github.com/htmlacademy-ecmascript/123003-big-trip-simple-19/pull/7#discussion_r1061572599
я тогда перенесу проверку на null в конструктор, это ок?

2023-01-04 22:46 UTC, JuliaAf commented on src/view/point-form-view.js
суть _Принцип единственной ответственности_ понятна
непонятно, как мне вынести в отдельную функцию все, что отвечает за данные. 
ты имеешь ввиду, вынести только данные по destinations? можно было бы создать отдельную функцию и там сделать деструктуризацию для destinations и возвращать эту разметку http://joxi.ru/GrqxPWlHz3wWQA, но тогда для http://joxi.ru/BA0Nk8QC15dQvm все равно надо будет деструктуризацию  для destinations 😕

2023-01-05 05:39 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#rollupButtonClickHandler);
Сейчас да, а далее желательно так, как [показано в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-6/src/view/task-edit-view.js#L193-L196).

2023-01-05 05:40 UTC, AlexMasterov commented on src/view/point-form-view.js
Функции не достаточно.

См. _на будущие_ [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-19/blob/module-6/src/view/task-edit-view.js#L268-L273).

2023-01-05 06:19 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    if (this.element.querySelector('.event__rollup-btn') !== null) {
Обработчик `#rollupButtonClickHandler` добавляется на событие клика по кнопке `.event__rollup-btn` и, соответственно, будет вызван на клик по ней. Чтобы добавить обработчик, в `this.element` должен быть узел с кнопкой `.event__rollup-btn`, который создается из разметки, в одном месте, а для порождения события он должен быть показан в браузере. 

Что должно случиться, что в момент вызова обработчика кнопки, по которой кликнули, _уже_ не было?

_Технически_ можно вне модуля отследить появление (мутацию) в DOM узла `.event__rollup-btn` и добавить на него еще один обработчик, настроив его при добавления так, чтобы он был выполнен в первую очередь, раньше `#rollupButtonClickHandler`. Тогда если в первом обработчик удалить узел `.event__rollup-btn`, то далее при выполнении `#rollupButtonClickHandler` его уже не будет.

Неужели ты пытаешься обработать подобный случай?

2023-01-05 10:52 UTC, JuliaAf commented on src/view/point-form-view.js
я тогда займусь этим в 6 модуле, пока не буду лезть вперед)

2023-01-05 10:57 UTC, JuliaAf commented on src/view/point-form-view.js
> +    if (this.element.querySelector('.event__rollup-btn') !== null) {
нет, я не подобный случай хотела обработать)  просто проверку добавила не там, где нужно)

2023-01-05 10:59 UTC, JuliaAf commented on src/view/point-form-view.js
а что за чат в тг ты имеешь ввиду?

2023-01-05 11:01 UTC, AlexMasterov commented on src/view/point-form-view.js
> а что за чат в тг ты имеешь ввиду?

ТГ = Телеграмм

2023-01-05 11:05 UTC, JuliaAf commented on src/view/point-form-view.js
я понимаю, какой именно чат?)

2023-01-05 11:15 UTC, JuliaAf commented on src/view/point-form-view.js
сорян, подумала, что в каком-то групповом чате)

2023-01-05 11:19 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.#rollupButton = this.element.querySelector('.event__rollup-btn');
```js
this.removeElement(); //  this.#element = null;

// Продолжает указывать на доч. узел '.event__rollup-btn':
this.#rollupButton // HTMLButtonElement
````

См. [Сборка мусора на основе подсчёта ссылок](https://developer.mozilla.org/ru/docs/Web/JavaScript/Memory_Management#%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0_%D0%BC%D1%83%D1%81%D0%BE%D1%80%D0%B0_%D0%BD%D0%B0_%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5_%D0%BF%D0%BE%D0%B4%D1%81%D1%87%D1%91%D1%82%D0%B0_%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA):
> Объект считается подлежащим уничтожению сборщиком мусора, если количество ссылок на него равно нулю

Пока объект `PointFormView` "жив", а его свойство указывает на доч. элемент, удаленного элемента узла `.trip-events__item`, то сборщик мусора не сможет очистить память. См. [Утечка памяти](https://ru.wikipedia.org/wiki/%D0%A3%D1%82%D0%B5%D1%87%D0%BA%D0%B0_%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8).

> Предупреждал об этом на консультации

2023-01-05 11:20 UTC, AlexMasterov commented on src/view/point-form-view.js
> +      this.#rollupButton.addEventListener('click', this.#rollupButtonClickHandler);
Вполне достаточно было сделать так:
```js
this.element.querySelector('.event__rollup-btn')?.addEventListener('click', this.#rollupButtonClickHandler);
```

2023-01-05 11:24 UTC, AlexMasterov commented on src/view/filter-view.js
> +      ${createFilterTemplate({ id: 'everything', checked: true })}
См. доп. ТЗ:
> Кнопка фильтра становится недоступной, если фильтру не соответствует ни одна из точек маршрута

Пожалуйста, так же добавь (интерфейсу) функции возможность задать фильтру `disabled`.

2023-01-05 11:25 UTC, AlexMasterov commented
👍🏻

2023-01-05 11:29 UTC, AlexMasterov commented on src/presenter/points-presenter.js
> +      document.removeEventListener('keydown', escKeyDownHandler);
Кода прибавилось, а дублирование осталось.

Далее попробуем исправить.

2023-01-05 11:40 UTC, AlexMasterov commented on src/view/filter-view.js
> +      ${createFilterTemplate({ id: 'everything', checked: true })}
![image](https://user-images.githubusercontent.com/700213/210772050-215b0fa9-3781-40ae-b400-49746bfe6c19.png)
![image](https://user-images.githubusercontent.com/700213/210772084-a7bdc06d-d4d7-4b07-a06e-8a3f52822025.png)

🤔

2023-01-05 11:41 UTC, AlexMasterov commented on src/view/filter-view.js
> +      ${createFilterTemplate({ id: 'everything', checked: true })}
Было/Стало:

![image](https://user-images.githubusercontent.com/700213/210772084-a7bdc06d-d4d7-4b07-a06e-8a3f52822025.png)
![image](https://user-images.githubusercontent.com/700213/210772050-215b0fa9-3781-40ae-b400-49746bfe6c19.png)

🤔

2023-01-05 12:38 UTC, JuliaAf commented on src/view/filter-view.js
> +      ${createFilterTemplate({ id: 'everything', checked: true })}
в стилях применяется капс, поэтому я подумала, что нет смысла в создании title

2023-01-05 13:20 UTC, JuliaAf commented on src/view/point-form-view.js
> +    this.#rollupButton = this.element.querySelector('.event__rollup-btn');
но ведь переменная тоже указывает на  доч. элемент удаленного элемента узла, в чем разница? я попробовала заменить на переменную, удалить элемент, а ссылки на кнопку все равно сохраняются http://joxi.ru/KAgdlN5T5Q344r

2023-01-05 13:37 UTC, AlexMasterov commented on src/view/point-form-view.js
> +    this.#rollupButton = this.element.querySelector('.event__rollup-btn');
`this.removeElement` не удаляет элемент из DOM.

Переменная будет удалена после выполнение функции-конструктора, а свойство/слот нет.

2023-01-05 13:58 UTC, merged